apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TluwaniMS/basic-node-js-web-server-deployment
    targetRevision: master
    path: kubernetes-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true