apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inline-helm-staging-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      values: |
        envPrefix: inline-staging
        deployment:
          replicas: 3
        container:
          image: basic-node-web-server
          tag: v1.3.0
    repoURL: https://github.com/TluwaniMS/basic-node-js-web-server-deployment
    targetRevision: master
    path: helm-app-manifests/basic-node-js-web-server
  destination:
    server: https://kubernetes.default.svc
    namespace: inline-staging-app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
